# zeros & ones 

###  0으로 채워진 numpy array 만들 수 있음


In [2]:
import numpy as np

In [4]:
np.zeros([3, 3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
zeros = np.zeros(1)
zeros

array([0.])

In [8]:
ones = np.ones([10, 5])
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
ones * 5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [12]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [13]:
arr = np.arange(4, 9)
arr

array([4, 5, 6, 7, 8])

In [16]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Broadcast

In [25]:
import numpy as np


In [26]:
arr = np.arange(9).reshape(3, 3)
arr


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
arr + 3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [28]:
arr * 3

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [29]:
arr  + np.array([1,1,1])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])