# 텐서플로우 간단한 사용법 

In [1]:
import numpy as np
import tensorflow as tf 


##  Tensor 생성 

In [3]:
tf.constant([1, 2, 3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

######  - 튜플로도 생성 가능 

In [4]:
tf.constant(((1,2,3), (1,2,3)))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3]], dtype=int32)>

#####  하지만 대부분은 Array 를 constant 에 담는 형식을 가장많이 사용하기때문에 , 


In [7]:
arr = [[1,2,3], [1,2,3]]
tensor = tf.constant(arr)
tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3]], dtype=int32)>

###  tensor 에 담기 정보 확인하기 

In [10]:
tensor.shape

TensorShape([2, 3])

In [11]:
tensor.dtype

tf.int32

###  nomal & uniform distribution

In [12]:
np.random.randn(9)

array([-1.03450596, -0.46339429,  0.80672776,  1.87275806,  0.19397515,
        0.02725301,  1.07294497, -1.64906085,  0.28200937])

In [14]:
tf.random.normal([3,3]) # nomal

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.8383241 , -0.6825628 ,  1.2531583 ],
       [ 1.4681847 , -0.4841743 ,  1.38864   ],
       [ 1.4839352 ,  1.0442705 , -0.29500625]], dtype=float32)>

In [16]:
tf.random.uniform([3,3]) # uniform

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.8353901 , 0.990427  , 0.25225902],
       [0.33423507, 0.36136925, 0.9517598 ],
       [0.32333982, 0.52493083, 0.21911204]], dtype=float32)>